version: '3'
services:

  mongodb:
    image: myregistry.local:80/mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongoData:/data/db
    restart: always

  panel:
    image: panel:1.0.0 
    ports:
      - "9090:9090"
    depends_on:
      - mongodb
    restart: always

  
  nginx:
    image: myregistry.local:80/library/nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - panel
    restart: always


  
volumes:
  mongoData:
